ip_space = "tf-demo"
dns_view = "tf-demo"
comment = "Terraform Deployment Demo"
parent_address_block = "192.168.0.0"
parent_address_block_cidr = 16
address_block_count = 5
address_block_size = 20
subnet_count = 15
subnet_size = 24