ip_space = "tf-ipspace"
dns_view = "tf-dnsview"
comment = "Terraform Deployment Demo"
parent_address_block = "10.100.0.0"
parent_address_block_cidr = 16
address_block_count = 5
address_block_size = 20
subnet_count = 15
subnet_size = 24
b1_api_key=${{B1DDI_API_KEY}}