trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: CmdLine@2
      displayName: 'Change Working Directory'
      inputs:
        script: |
          cd ./BloxOneDDI-Deploy
          ls -l

    - task: TerraformTaskV4@4
      displayName: Initialize Terraform
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure-infobloxlab'
        backendAzureRmResourceGroupName: 'infobloxlab'
        backendAzureRmStorageAccountName: 'sainfobloxlab'
        backendAzureRmContainerName: 'deploy-demo'
        backendAzureRmKey: 'state.tfstate'

    - task: TerraformTaskV4@4
      name: terraformPlan
      displayName: Create Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out main.tfplan -var-file="./BloxOneDDI-Deploy/demo.tfvars"'
        environmentServiceNameAzureRM: 'azure-infobloxlab'

- stage: Apply
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - task: TerraformTaskV4@4
      name: terraformApply
      displayName: Apply Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'main.tfplan -var-file="./BloxOneDDI-Deploy/demo.tfvars"'
        environmentServiceNameAzureRM: 'azure-infobloxlab'

- stage: Destroy
  displayName: 'Terraform Destroy'
  jobs:
  - job: TerraformDestroy
    displayName: 'Terraform Destroy'
    steps:
    - task: TerraformTaskV4@4
      name: terraformDestroy
      displayName: Destroy Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        commandOptions: 'main.tfplan -var-file="./BloxOneDDI-Deploy/demo.tfvars"'
        environmentServiceNameAzureRM: 'azure-infobloxlab'