parameters:
- name: action
  displayName: Terraform Action
  type: string
  default: Plan
  values:
  - Plan
  - Apply
  - Destroy

trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  condition: ${{ or(eq(parameters.action, 'Plan'), eq(parameters.action, 'Apply')) }}
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformTaskV4@4
      displayName: Initialize Terraform
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure-infobloxlab'
        backendAzureRmResourceGroupName: 'infobloxlab'
        backendAzureRmStorageAccountName: 'sainfobloxlab'
        backendAzureRmContainerName: 'deploy-demo'
        backendAzureRmKey: 'state.tfstate'
        workingDirectory: 'BloxOneDDI-Deploy'

    - task: TerraformTaskV4@4
      name: terraformPlan
      displayName: Create Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out main.tfplan --var-file=demo.tfvars -var b1_api_key=$(B1DDI_API_KEY)'
        workingDirectory: 'BloxOneDDI-Deploy'
        environmentServiceNameAzureRM: 'azure-infobloxlab'

    - publish: $(System.DefaultWorkingDirectory)/BloxOneDDI-Deploy/main.tfplan
      displayName: Publish Terraform Plan
      artifact: plan

- stage: Apply
  condition: ${{ eq(parameters.action, 'Apply') }}
  displayName: 'Terraform Apply'
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    - download: current
      displayName: Download Terraform Plan
      artifact: plan

    - task: TerraformTaskV4@4
      displayName: Initialize Terraform
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure-infobloxlab'
        backendAzureRmResourceGroupName: 'infobloxlab'
        backendAzureRmStorageAccountName: 'sainfobloxlab'
        backendAzureRmContainerName: 'deploy-demo'
        backendAzureRmKey: 'state.tfstate'
        workingDirectory: 'BloxOneDDI-Deploy'

    - task: TerraformTaskV4@4
      name: terraformApply
      displayName: Apply Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '$(Pipeline.Workspace)/plan/main.tfplan'
        workingDirectory: 'BloxOneDDI-Deploy'
        environmentServiceNameAzureRM: 'azure-infobloxlab'

- stage: Destroy
  condition: ${{ eq(parameters.action, 'Destroy') }}
  displayName: 'Terraform Destroy'
  jobs:
  - job: TerraformDestroy
    displayName: 'Terraform Destroy'
    steps:
    - task: TerraformTaskV4@4
      displayName: Initialize Terraform
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'azure-infobloxlab'
        backendAzureRmResourceGroupName: 'infobloxlab'
        backendAzureRmStorageAccountName: 'sainfobloxlab'
        backendAzureRmContainerName: 'deploy-demo'
        backendAzureRmKey: 'state.tfstate'
        workingDirectory: 'BloxOneDDI-Deploy'
      
    - task: TerraformTaskV4@4
      name: terraformDestroy
      displayName: Destroy Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: 'BloxOneDDI-Deploy'
        environmentServiceNameAzureRM: 'azure-infobloxlab'